# Generated by Django 5.2.7 on 2025-10-14 16:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=7, unique=True, verbose_name='Placa do Veículo')),
                ('marca', models.CharField(max_length=50)),
                ('modelo', models.CharField(max_length=100)),
                ('ano', models.IntegerField(verbose_name='Ano Fabricação')),
                ('quilometragem', models.IntegerField()),
                ('cor', models.CharField(max_length=30)),
                ('status', models.CharField(choices=[('AVALIACAO', 'Em Avaliação'), ('COMPRADO', 'Comprado - Em Preparação'), ('ESTOQUE', 'Em Estoque - Pronto para Venda'), ('VENDIDO', 'Vendido')], default='AVALIACAO', max_length=20)),
                ('data_entrada', models.DateTimeField(auto_now_add=True, verbose_name='Data de Entrada na Avaliação')),
                ('data_compra', models.DateTimeField(blank=True, null=True, verbose_name='Data da Compra Efetiva')),
                ('data_venda', models.DateTimeField(blank=True, null=True, verbose_name='Data da Venda')),
                ('preco_compra', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Preço Pago')),
                ('preco_anuncio', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Preço Anunciado')),
                ('avaliador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Avaliador/Comprador')),
            ],
        ),
        migrations.CreateModel(
            name='WorkflowEtapa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True)),
                ('ordem', models.IntegerField(unique=True, verbose_name='Ordem no Kanban')),
            ],
            options={
                'ordering': ['ordem'],
            },
        ),
        migrations.CreateModel(
            name='AvaliacaoPreditiva',
            fields=[
                ('veiculo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='veiculos.veiculo')),
                ('preco_maximo_compra', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='PMC Sugerido pela IA')),
                ('tmv_previsto_dias', models.IntegerField(verbose_name='TMV Previsto (dias)')),
                ('margem_desejada', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Margem Desejada (%)')),
                ('fipe_referencia', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço Tabela FIPE')),
                ('mercado_medio_concorrencia', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Médio Concorrência')),
                ('data_avaliacao', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='WorkflowItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tmv_prioridade', models.IntegerField(verbose_name='Prioridade (Baseada no TMV)')),
                ('data_inicio_etapa', models.DateTimeField(auto_now=True)),
                ('etapa_atual', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='veiculos.workflowetapa')),
                ('responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('veiculo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='veiculos.veiculo')),
            ],
        ),
    ]
