# Generated by Django 5.2.7 on 2025-10-15 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veiculos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModeloVeiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=50)),
                ('nome_modelo', models.CharField(max_length=100)),
            ],
            options={
                'unique_together': {('marca', 'nome_modelo')},
            },
        ),
    ]
